{{- if .Values.tlssnihostnameref.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Release.Name }}-uasni-configmap'
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation
data: # OMS Configuration Map -- ONLY ENVIRONMENT VARIABLES FOR SNI SUPPORT
  UAGTLSSNIHOSTNAME: ""
{{- end }}