apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Release.Name }}-ua-configmap'
  namespace: {{ .Release.Namespace }}
data: # OMS Configuration Map -- ONLY ENVIRONMENT VARIABLES SUPPORTED: Order of Components -> UAG -> OMS -> UBR -> UEM -> UDM
  UAGTLSSNIHOSTNAME: "{{ .Values.istio.udmConnectionPort }}@{{ .Values.istio.host }}:{{ .Values.istio.host }}"
  UAGTRANSIENT: "yes"
  {{ include "uac.emitIfSet" (dict "name" "UAGAGENTCLUSTERS" "value" .Values.uaConfig.uagagentclusters) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UAGBUSINESSSERVICES" "value" .Values.uaConfig.businessservices) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UAGEXTACCEPTLIST" "value" .Values.uaConfig.extensionacceptlist) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UAGEXTCANCELTIMEOUT" "value" .Values.uaConfig.extensioncanceltimeout) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UAGEXTDEPLOYONREG" "value" .Values.uaConfig.extensiondeployonregistration) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UAGEXTPYTHONLIST" "value" .Values.uaConfig.extensionpythonlist) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UAGNETNAME" "value" .Values.uaConfig.netname) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UAGOMSSERVERS" "value" .Values.uaConfig.omsServers) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UAGPRCCANCELTIMEOUT" "value" .Values.uaConfig.processcanceltimeout) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UAGAUTOSTART" "value" .Values.uaConfig.uagAutostart) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UAGLOGLVL" "value" .Values.uaConfig.uagLoglvl) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UAGLEVEL" "value" .Values.uaConfig.uagLevel) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OMSCODEPAGE" "value" .Values.uaConfig.codepage) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OMSDNSCACHETIMEOUT" "value" .Values.uaConfig.omsDNSCacheTimeout) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OMSINDEXCACHESIZE" "value" .Values.uaConfig.omsIndexCacheSize) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OMSMAXCONNECTIONS" "value" .Values.uaConfig.omsMaxConnections) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OMSMAXDATAFILESIZE" "value" .Values.uaConfig.maxfilesize) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OMSMAXMSGSIZE" "value" .Values.uaConfig.maxmessagesize) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OMSMAXSSLPROTOCOL" "value" .Values.uaConfig.omsMaxSSLProtocol) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OMSLANG" "value" .Values.uaConfig.omsLanguage) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OMSMINSSLPROTOCOL" "value" .Values.uaConfig.omsMinSSLProtocol) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OMSMSGCHUNKSIZE" "value" .Values.uaConfig.chunksize) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OMSMSGCLEANUPINTERVAL" "value" .Values.uaConfig.omsMSGCleanupInterval) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OMSMSGDATAFLUSHINT" "value" .Values.uaConfig.omsMSGDataFlushInt) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OMSMSGSUPPRESSIONLIST" "value" .Values.uaConfig.omsMSGSuppressionList) | nindent 2 }}

  {{ include "uac.emitIfSet" (dict "name" "OTEL_ENABLE_TRACING" "value" .Values.uaConfig.otelenabletracing) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OTEL_EXPORT_METRICS" "value" .Values.uaConfig.otelexportmetrics) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OTEL_METRICS_ENDPOINT" "value" .Values.uaConfig.otelmetricsendpoint) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OTEL_METRICS_EXPORT_INTERVAL" "value" .Values.uaConfig.otelmetricsexportinterval) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OTEL_SERVICE_NAME" "value" .Values.uaConfig.otelservicename) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OTEL_SSL_CA_CERT_PATH" "value" .Values.uaConfig.otelsslcacertpath) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OTEL_SSL_CLIENT_CERT_PATH" "value" .Values.uaConfig.otelsslclientcertpath) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OTEL_SSL_CLIENT_KEY_PATH" "value" .Values.uaConfig.otelsslclientkeypath) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OTEL_SSL_INSECURE_SKIP_VERIFY" "value" .Values.uaConfig.otelsslinsecureskipverify) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OTEL_TRACE_ENDPOINT" "value" .Values.uaConfig.oteltraceendpoint) | nindent 2 }}

  {{ include "uac.emitIfSet" (dict "name" "OMSREQUIRESSL" "value" .Values.uaConfig.omsRequiresSSL) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OMSSERVICEBACKLOG" "value" .Values.uaConfig.omsServiceBacklog) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OMSSVCIPADDR" "value" .Values.uaConfig.omsSVCIAddr) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OMSSVCPORT" "value" .Values.uaConfig.omsSVCIPort) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OMSSERVICETIMEOUT" "value" .Values.uaConfig.omsServiceTimeout) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OMSSSLCIPHERLIST" "value" .Values.uaConfig.sslcipherlist) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OMSSSLCIPHERSUITES" "value" .Values.uaConfig.sslciphersuites) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OMSTRACEFILELINES" "value" .Values.uaConfig.omstracefilelines) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OMSTRACETABLE" "value" .Values.uaConfig.omstracetable) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "OMSAUTOSTART" "value" .Values.uaConfig.omsAutostart) | nindent 2 }}

  {{ include "uac.emitIfSet" (dict "name" "UBRACTIVITYMONITORING" "value" .Values.uaConfig.ubractivitymonitoring) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRCACERTS" "value" .Values.uaConfig.ubrcacerts) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRCERT" "value" .Values.uaConfig.ubrcert) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRCRL" "value" .Values.uaConfig.ubrcrl) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRCODEPAGE" "value" .Values.uaConfig.codepage) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRCOMPINFORETENTION" "value" .Values.uaConfig.ubrcompinforetention) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRCOMPONENTBACKLOG" "value" .Values.uaConfig.ubrcomponentbacklog) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRCMPPORT" "value" .Values.uaConfig.ubrcmpport) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRCTLSSLCIPHERLIST" "value" .Values.uaConfig.sslcipherlist) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRCTLSSLCIPHERSUITES" "value" .Values.uaConfig.sslciphersuites) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRDBFILEGENERATIONS" "value" .Values.uaConfig.ubrdbfilegenerations) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRDNSCACHETIMEOUT" "value" .Values.uaConfig.ubrdnscachetimeout) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRECDSACERT" "value" .Values.uaConfig.ubrecdsacert) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRECDSAPRIVATEKEYPWD" "value" .Values.uaConfig.ubrecdsaprivatekeypwd) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRECDSAPRIVATEKEY" "value" .Values.uaConfig.ubrecdsaprivatekey) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBREVENTGENERATION" "value" .Values.uaConfig.ubreventgeneration) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRMAXSSLPROTOCOL" "value" .Values.uaConfig.omsMaxSSLProtocol) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRDEST" "value" .Values.uaConfig.ubrdest) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRLANG" "value" .Values.uaConfig.omsLanguage) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRLEVEL" "value" .Values.uaConfig.ubrlevel) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRMINSSLPROTOCOL" "value" .Values.uaConfig.omsMinSSLProtocol) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRMONITOREVENTEXP" "value" .Values.uaConfig.ubrmonitoreventexp) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRMOUNTPOINT" "value" .Values.uaConfig.ubrmountpoint) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRMOUNTPOINTMODE" "value" .Values.uaConfig.ubrmountpointmode) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRMSGSUPPRESSIONLIST" "value" .Values.uaConfig.ubrmsgsuppressionlist) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRPERSISTENTEVENTEXP" "value" .Values.uaConfig.ubrpersistenteventexp) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRPRIVATEKEY" "value" .Values.uaConfig.ubrprivatekey) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRPRIVATEKEYPWD" "value" .Values.uaConfig.ubrprivatekeypwd) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRREQUIRESSL" "value" .Values.uaConfig.omsRequiresSSL) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRRETRYMAXCOMP" "value" .Values.uaConfig.ubrretrymaxcomp) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRSAFKEYRING" "value" .Values.uaConfig.ubrsafkeyring) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRSAFKEYRINGLABEL" "value" .Values.uaConfig.ubrsafkeyringlabel) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRSERVICEBACKLOG" "value" .Values.uaConfig.ubrservicebacklog) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRSVCIPADDR" "value" .Values.uaConfig.ubrsvcipaddr) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRSVCPORT" "value" .Values.uaConfig.ubrsvcport) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRSHRMOUNTPOINT" "value" .Values.uaConfig.ubrshrmountpoint) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRSHRMOUNTPOINTMODE" "value" .Values.uaConfig.ubrshrmountpointmode) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRSMFEXITLOADLIBRARY" "value" .Values.uaConfig.ubrsmfexitloadlibrary) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRSSLIMPLEMENTATION" "value" .Values.uaConfig.ubrsslimplementation) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRSYSTEMID" "value" .Values.uaConfig.ubrsystemid) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRTCPRECVBUFFER" "value" .Values.uaConfig.ubrtcprecvbuffer) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRTCPSENDBUFFER" "value" .Values.uaConfig.ubrtcpsendbuffer) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRTRACEFILELINES" "value" .Values.uaConfig.ubrtracefilelines) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UCMDTRACETABLE" "value" .Values.uaConfig.ucmdtracetable) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRUCMDSTCSUPPORT" "value" .Values.uaConfig.ubrucmdstcsupport) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UBRUCMDPATH" "value" .Values.uaConfig.ubrucmdpath) | nindent 2 }}

  {{ include "uac.emitIfSet" (dict "name" "UEMAUTOSTART" "value" .Values.uaConfig.uemAutostart) | nindent 2 }}

  {{ include "uac.emitIfSet" (dict "name" "UDMACKWINDOW" "value" .Values.uaConfig.udmackwindow) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMALLOWREPLONRENAME" "value" .Values.uaConfig.udmallowreplonrename) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMBIFDIRECTORY" "value" .Values.uaConfig.udmbifdirectory) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMCACERTS" "value" .Values.uaConfig.udmcacerts) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMCERT" "value" .Values.uaConfig.udmcert) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMDAYSTILEXPIRE" "value" .Values.uaConfig.udmdaystilexpire) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMCRL" "value" .Values.uaConfig.udmcrl) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMCODEPAGE" "value" .Values.uaConfig.codepage) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMCTLSSLCIPHERLIST" "value" .Values.uaConfig.sslcipherlist) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMCTLSSLCIPHERSUITES" "value" .Values.uaConfig.sslciphersuites) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMENCRYPT" "value" .Values.uaConfig.udmencrypt) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMFRAMEINTERVAL" "value" .Values.uaConfig.udmframeinterval) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMIDLETIMEOUT" "value" .Values.uaConfig.udmidletimeout) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMKEEPALIIVEINTERVAL" "value" .Values.uaConfig.udmkeepaliveinterval) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMMAXSSLPROTOCOL" "value" .Values.uaConfig.omsMaxSSLProtocol) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMMERGELOG" "value" .Values.uaConfig.udmmergelog) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMLANG" "value" .Values.uaConfig.omsLanguage) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMLEVEL" "value" .Values.uaConfig.udmlevel) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMMINSSLPROTOCOL" "value" .Values.uaConfig.omsMinSSLProtocol) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMMODETYPE" "value" .Values.uaConfig.udmmodetype) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMMSGSUPPRESSIONLIST" "value" .Values.uaConfig.udmmsgsuppressionlist) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMDELAY" "value" .Values.uaConfig.udmdelay) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMNETWORKFAULTTOLERANT" "value" .Values.uaConfig.udmnetworkfaulttolerant) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMOPENRETRY" "value" .Values.uaConfig.udmopenretry) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMOPENRETRYCOUNT" "value" .Values.uaConfig.udmopenretrycount) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMOPENRETRYINTERVAL" "value" .Values.uaConfig.udmopenretryinterval) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMOUTBOUNDIP" "value" .Values.uaConfig.udmoutboundip) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMPLFDIRECTORY" "value" .Values.uaConfig.udmplfdirectory) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMPRIVATEKEY" "value" .Values.uaConfig.udmprivatekey) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMPRIVATEKEYPWD" "value" .Values.uaConfig.udmprivatekeypwd) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMPROXYCERTIFICATES" "value" .Values.uaConfig.udmproxycertificates) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMRETRYCOUNT" "value" .Values.uaConfig.udmretrycount) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMRETRYINTERVAL" "value" .Values.uaConfig.udmretryinterval) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMRECVBUFSSIZE" "value" .Values.uaConfig.udmrecvbufssize) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMPORT" "value" .Values.uaConfig.udmport) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMSAFKEYRING" "value" .Values.uaConfig.udmsafkeyring) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMSAFKEYRINGLABEL" "value" .Values.uaConfig.udmsafkeyringlabel) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMSCRIPT" "value" .Values.uaConfig.udmscript) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMOPTIONS" "value" .Values.uaConfig.udmoptions) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMSENDBUFSSIZE" "value" .Values.uaConfig.udmsendbufssize) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMSERVERSTOPCONDITIONS" "value" .Values.uaConfig.udmserverstopconditions) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMSIZEATTRIB" "value" .Values.uaConfig.udmsizeattrib) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMSSLIMPLEMENTATION" "value" .Values.uaConfig.udmsslimplementation) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMSYSTEMID" "value" .Values.uaConfig.udmsystemid) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMTCPNODELAY" "value" .Values.uaConfig.udmtcpnodelay) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMTCPRECVBUFFER" "value" .Values.uaConfig.udmtcprecvbuffer) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMTCPSENDBUFFER" "value" .Values.uaConfig.udmtcpsendbuffer) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMTRACEFILELINES" "value" .Values.uaConfig.udmtracefilelines) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMTRACETABLE" "value" .Values.uaConfig.udmtracetable) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMUCMDPATH" "value" .Values.uaConfig.udmucmdpath) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMUMASK" "value" .Values.uaConfig.udmumask) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMUSAPDPATH" "value" .Values.uaConfig.udmusapdpath) | nindent 2 }}
  {{ include "uac.emitIfSet" (dict "name" "UDMVERIFYHOSTNAME" "value" .Values.uaConfig.udmverifyhostname) | nindent 2 }}
