{{- if .Values.omsDeployment.enabled }}
# one service, two ports for OMS and UDM
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-oms-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "universal-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: oms-service
spec:
  selector:
    app.kubernetes.io/name: {{ include "universal-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: oms
  ports:
    - name: oms
      port: 7878
      targetPort: 7878
      protocol: TCP
{{- end }}
---
{{- if .Values.omsDeployment.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-udm-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "universal-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: udm-service
spec:
  selector:
    {{- include "universal-controller.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: udm
  ports:
    - name: udm
      port: 7887
      targetPort: 7887
      protocol: TCP
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-uc-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "universal-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: uc-service
spec:
  selector:
    app.kubernetes.io/name: {{ include "universal-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: uc
  ports:
    - name: {{ .Release.Name }}-uc-port
      protocol: TCP
      port: 80
      targetPort: 8080
