{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- with .Values.ingress.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  name: '{{ .Release.Name }}-ua-ingress'
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: '{{ .Values.ingress.hostName }}'
    http:
      paths:
      - backend:
          service:
            name: '{{ .Release.Name }}-ua-service'
            port:
              number: {{ .Values.services.uaService.targetPort | int }}
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.ingress.hostName }}
    secretName: {{ .Values.ingress.tlsSecretName }}
{{- end }}