# templates/oms-deployment.yaml
{{- if .Values.oms.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-oms
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "universal-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: oms
spec:
  replicas: {{ .Values.omsDeployment.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "universal-controller.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: oms
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"  # Disable Istio sidecar for TLS PASSTHROUGH
      labels:
        app.kubernetes.io/name: {{ include "universal-controller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: oms
    spec:
      serviceAccountName: {{ include "universal-controller.serviceAccountName" . }}
      securityContext:
        fsGroup: 0
        runAsUser: 1000
        runAsGroup: 1000
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: uac-oms
          image: "{{ .Values.omsDeployment.image.repository }}:{{ .Values.omsDeployment.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7878
            - containerPort: 7887
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-oms-configmap
          volumeMounts:
            - name: oms-storage
              mountPath: "/var/opt/universal/spool/oms"
          resources: {{- toYaml .Values.omsDeployment.resources | nindent 12 }}
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  pgrep -x omssrv >/dev/null ||
                  pgrep -x ubroker >/dev/null ||
                  pgrep -x uagsrv >/dev/null ||
                  pgrep -x uemsrv >/dev/null
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  pgrep -x omssrv >/dev/null ||
                  pgrep -x ubroker >/dev/null ||
                  pgrep -x uagsrv >/dev/null ||
                  pgrep -x uemsrv >/dev/null
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: oms-storage
          persistentVolumeClaim:
            claimName: '{{ .Release.Name }}-oms-pvc'
{{- end }}
